#!/bin/sh
set -e

custom_php_config(){
	echo "Set custom php configurations"
	$(which envsubst) < /docker/config/conf.d/app.ini > /usr/local/etc/php/conf.d/app.ini
}

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	custom_php_config
	set -- php-fpm "$@"
else

	if [ $1 == "php-fpm" ]
	then
		custom_php_config
	fi

	echo "CMD: $@"
fi

exec "$@"